version: 1
services:
  web:
    image: railway/app-runner-nodejs
    build:
      path: .
    env:
      NODE_ENV: production
      DATABASE_URL: mysql://root:password@hostname/dronedb
    ports:
      - 5000
